spring.application.name=J2AutoParts
spring.datasource.url=jdbc:mysql://localhost:3306/j2AutoParts?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=16

server.port=8080


app.jwt.secret=7a8f3c2e9b1d4a6e8f0c2b4d6a8e0c2f4b6d8a0c2e4f6b8d0a2c4e6f8b0d2a4
app.jwt.expiration-ms=86400000